version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000